title: eugenio1091.github.io
description: A minimal and beautiful Jekyll theme best for writing and note-taking.
author: eugenio1091.github.io
avatar: /logo.png.png
email: stefanut_eugen@protonmail.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec


